let currentImageUrl = null;
let currentImageId = null;

// Wait till page is fully  loaded
$(document).ready(function () {

    $('.image-items form').on('submit', function (e) {
        e.preventDefault();

        const email = getUserEmail();
        if (!email) return;

        const query = $('#search').val().trim();

        if (query === "") {
            showMessage("Please enter a search query!", "error");
            return;
        }

        generateImage(query, email);
    });
});

function generateImage(query, email) {
    const accessKey = 'oPGqjh7ugOIO2BnXu0o0sBnPqvD3sDnviElQBZSOqlI'; // remove in github

    // Using AJAX to request the Unsplash API
    $.ajax({
        url: 'https://api.unsplash.com/photos/random',
        method: 'GET',
        data: {
            query: query,   // Search keyword
            client_id: accessKey
        },

        // If API call is successfull
        success: function(data)  {
            const imageUrl = data.urls.regular; // Extracts image URL
            const photographer  = data.user.name;   // Gets photographer name
            const profileLink = data.user.links.html;   // Gets photographers link
            const imageId = data.id; // Gets ID

            // Saves user's email and the imageUrl
            currentImageUrl = imageUrl;
            
            currentImageId = imageId;

            $('#image-container').html(`
                <br>
                <img src="${imageUrl}" alt="An image generated by the Unsplash API">
                <p>
                    Photo by <a href="${profileLink}" target="_blank">
                    ${photographer}</a> on Unsplash
                </p>
                `);
        },
        
        // Runs if API call fails
        error: function () {
            showMessage("Something Failed", "error")
        }
    })
}